/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IFixrFeeSplitter__factory } from "./IFixrFeeSplitter__factory";
export { IFixrStaking__factory } from "./IFixrStaking__factory";
