/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace FarcasterOracle {
  export type SocialMetricsStruct = {
    mentions24h: BigNumberish;
    sentimentScore: BigNumberish;
    engagementRate: BigNumberish;
    uniqueUsers: BigNumberish;
    totalEngagement: BigNumberish;
    topCastFid: BigNumberish;
    timestamp: BigNumberish;
  };

  export type SocialMetricsStructOutput = [
    mentions24h: bigint,
    sentimentScore: bigint,
    engagementRate: bigint,
    uniqueUsers: bigint,
    totalEngagement: bigint,
    topCastFid: bigint,
    timestamp: bigint
  ] & {
    mentions24h: bigint;
    sentimentScore: bigint;
    engagementRate: bigint;
    uniqueUsers: bigint;
    totalEngagement: bigint;
    topCastFid: bigint;
    timestamp: bigint;
  };
}

export interface FarcasterOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "consensusThreshold"
      | "currentSubmissions"
      | "getCurrentSubmissionCount"
      | "getLatestMetrics"
      | "getSubmission"
      | "hasSubmittedThisRound"
      | "isValidator"
      | "lastUpdate"
      | "latestMetrics"
      | "name"
      | "needsUpdate"
      | "owner"
      | "registry"
      | "renounceOwnership"
      | "submitMetrics"
      | "symbol"
      | "targetToken"
      | "transferOwnership"
      | "updateFrequency"
      | "updateValidators"
      | "validatorSubmissionCount"
      | "validators"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ConsensusReached"
      | "MetricsSubmitted"
      | "OwnershipTransferred"
      | "ValidatorsUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "consensusThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentSubmissions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentSubmissionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLatestMetrics",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSubmission",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasSubmittedThisRound",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastUpdate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "latestMetrics",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "needsUpdate",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitMetrics",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "targetToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateFrequency",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateValidators",
    values: [[AddressLike, AddressLike, AddressLike, AddressLike, AddressLike]]
  ): string;
  encodeFunctionData(
    functionFragment: "validatorSubmissionCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "validators",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "consensusThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentSubmissions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentSubmissionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLatestMetrics",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubmission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasSubmittedThisRound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lastUpdate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "latestMetrics",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "needsUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitMetrics",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "targetToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateFrequency",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateValidators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validatorSubmissionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "validators", data: BytesLike): Result;
}

export namespace ConsensusReachedEvent {
  export type InputTuple = [
    mentions24h: BigNumberish,
    sentimentScore: BigNumberish,
    engagementRate: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    mentions24h: bigint,
    sentimentScore: bigint,
    engagementRate: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    mentions24h: bigint;
    sentimentScore: bigint;
    engagementRate: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MetricsSubmittedEvent {
  export type InputTuple = [
    validator: AddressLike,
    mentions24h: BigNumberish,
    sentimentScore: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    validator: string,
    mentions24h: bigint,
    sentimentScore: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    validator: string;
    mentions24h: bigint;
    sentimentScore: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidatorsUpdatedEvent {
  export type InputTuple = [
    validators: [
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike
    ]
  ];
  export type OutputTuple = [
    validators: [string, string, string, string, string]
  ];
  export interface OutputObject {
    validators: [string, string, string, string, string];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FarcasterOracle extends BaseContract {
  connect(runner?: ContractRunner | null): FarcasterOracle;
  waitForDeployment(): Promise<this>;

  interface: FarcasterOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  consensusThreshold: TypedContractMethod<[], [bigint], "view">;

  currentSubmissions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, FarcasterOracle.SocialMetricsStructOutput, bigint, boolean] & {
        validator: string;
        metrics: FarcasterOracle.SocialMetricsStructOutput;
        timestamp: bigint;
        processed: boolean;
      }
    ],
    "view"
  >;

  getCurrentSubmissionCount: TypedContractMethod<[], [bigint], "view">;

  getLatestMetrics: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        mentions24h: bigint;
        sentimentScore: bigint;
        engagementRate: bigint;
        uniqueUsers: bigint;
        totalEngagement: bigint;
        topCastFid: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getSubmission: TypedContractMethod<
    [index: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint] & {
        validator: string;
        mentions24h: bigint;
        sentimentScore: bigint;
        engagementRate: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  hasSubmittedThisRound: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  isValidator: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  lastUpdate: TypedContractMethod<[], [bigint], "view">;

  latestMetrics: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        mentions24h: bigint;
        sentimentScore: bigint;
        engagementRate: bigint;
        uniqueUsers: bigint;
        totalEngagement: bigint;
        topCastFid: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  name: TypedContractMethod<[], [string], "view">;

  needsUpdate: TypedContractMethod<[], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  registry: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  submitMetrics: TypedContractMethod<
    [
      _mentions24h: BigNumberish,
      _sentimentScore: BigNumberish,
      _engagementRate: BigNumberish,
      _uniqueUsers: BigNumberish,
      _totalEngagement: BigNumberish,
      _topCastFid: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  targetToken: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateFrequency: TypedContractMethod<[], [bigint], "view">;

  updateValidators: TypedContractMethod<
    [
      _validators: [
        AddressLike,
        AddressLike,
        AddressLike,
        AddressLike,
        AddressLike
      ]
    ],
    [void],
    "nonpayable"
  >;

  validatorSubmissionCount: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  validators: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "consensusThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "currentSubmissions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, FarcasterOracle.SocialMetricsStructOutput, bigint, boolean] & {
        validator: string;
        metrics: FarcasterOracle.SocialMetricsStructOutput;
        timestamp: bigint;
        processed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCurrentSubmissionCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLatestMetrics"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        mentions24h: bigint;
        sentimentScore: bigint;
        engagementRate: bigint;
        uniqueUsers: bigint;
        totalEngagement: bigint;
        topCastFid: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSubmission"
  ): TypedContractMethod<
    [index: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint] & {
        validator: string;
        mentions24h: bigint;
        sentimentScore: bigint;
        engagementRate: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasSubmittedThisRound"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isValidator"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastUpdate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "latestMetrics"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        mentions24h: bigint;
        sentimentScore: bigint;
        engagementRate: bigint;
        uniqueUsers: bigint;
        totalEngagement: bigint;
        topCastFid: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "needsUpdate"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitMetrics"
  ): TypedContractMethod<
    [
      _mentions24h: BigNumberish,
      _sentimentScore: BigNumberish,
      _engagementRate: BigNumberish,
      _uniqueUsers: BigNumberish,
      _totalEngagement: BigNumberish,
      _topCastFid: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "targetToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateFrequency"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "updateValidators"
  ): TypedContractMethod<
    [
      _validators: [
        AddressLike,
        AddressLike,
        AddressLike,
        AddressLike,
        AddressLike
      ]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "validatorSubmissionCount"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "validators"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getEvent(
    key: "ConsensusReached"
  ): TypedContractEvent<
    ConsensusReachedEvent.InputTuple,
    ConsensusReachedEvent.OutputTuple,
    ConsensusReachedEvent.OutputObject
  >;
  getEvent(
    key: "MetricsSubmitted"
  ): TypedContractEvent<
    MetricsSubmittedEvent.InputTuple,
    MetricsSubmittedEvent.OutputTuple,
    MetricsSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ValidatorsUpdated"
  ): TypedContractEvent<
    ValidatorsUpdatedEvent.InputTuple,
    ValidatorsUpdatedEvent.OutputTuple,
    ValidatorsUpdatedEvent.OutputObject
  >;

  filters: {
    "ConsensusReached(uint256,int256,uint256,uint256)": TypedContractEvent<
      ConsensusReachedEvent.InputTuple,
      ConsensusReachedEvent.OutputTuple,
      ConsensusReachedEvent.OutputObject
    >;
    ConsensusReached: TypedContractEvent<
      ConsensusReachedEvent.InputTuple,
      ConsensusReachedEvent.OutputTuple,
      ConsensusReachedEvent.OutputObject
    >;

    "MetricsSubmitted(address,uint256,int256,uint256)": TypedContractEvent<
      MetricsSubmittedEvent.InputTuple,
      MetricsSubmittedEvent.OutputTuple,
      MetricsSubmittedEvent.OutputObject
    >;
    MetricsSubmitted: TypedContractEvent<
      MetricsSubmittedEvent.InputTuple,
      MetricsSubmittedEvent.OutputTuple,
      MetricsSubmittedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ValidatorsUpdated(address[5])": TypedContractEvent<
      ValidatorsUpdatedEvent.InputTuple,
      ValidatorsUpdatedEvent.OutputTuple,
      ValidatorsUpdatedEvent.OutputObject
    >;
    ValidatorsUpdated: TypedContractEvent<
      ValidatorsUpdatedEvent.InputTuple,
      ValidatorsUpdatedEvent.OutputTuple,
      ValidatorsUpdatedEvent.OutputObject
    >;
  };
}
