/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface OracleFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "deployFarcasterOracle"
      | "deployPriceOracle"
      | "getValidators"
      | "registry"
      | "setValidators"
      | "validators"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "OracleDeployed"): EventFragment;

  encodeFunctionData(
    functionFragment: "deployFarcasterOracle",
    values: [string, string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deployPriceOracle",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getValidators",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setValidators",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "validators",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "deployFarcasterOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployPriceOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getValidators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setValidators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "validators", data: BytesLike): Result;
}

export namespace OracleDeployedEvent {
  export type InputTuple = [
    oracleAddress: AddressLike,
    creator: AddressLike,
    name: string,
    symbol: string
  ];
  export type OutputTuple = [
    oracleAddress: string,
    creator: string,
    name: string,
    symbol: string
  ];
  export interface OutputObject {
    oracleAddress: string;
    creator: string;
    name: string;
    symbol: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface OracleFactory extends BaseContract {
  connect(runner?: ContractRunner | null): OracleFactory;
  waitForDeployment(): Promise<this>;

  interface: OracleFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deployFarcasterOracle: TypedContractMethod<
    [
      _name: string,
      _symbol: string,
      _targetToken: string,
      _consensusThreshold: BigNumberish,
      _updateFrequency: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  deployPriceOracle: TypedContractMethod<
    [
      _name: string,
      _symbol: string,
      _consensusThreshold: BigNumberish,
      _updateFrequency: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  getValidators: TypedContractMethod<[], [string[]], "view">;

  registry: TypedContractMethod<[], [string], "view">;

  setValidators: TypedContractMethod<
    [_validators: AddressLike[]],
    [void],
    "nonpayable"
  >;

  validators: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deployFarcasterOracle"
  ): TypedContractMethod<
    [
      _name: string,
      _symbol: string,
      _targetToken: string,
      _consensusThreshold: BigNumberish,
      _updateFrequency: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deployPriceOracle"
  ): TypedContractMethod<
    [
      _name: string,
      _symbol: string,
      _consensusThreshold: BigNumberish,
      _updateFrequency: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getValidators"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setValidators"
  ): TypedContractMethod<[_validators: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "validators"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getEvent(
    key: "OracleDeployed"
  ): TypedContractEvent<
    OracleDeployedEvent.InputTuple,
    OracleDeployedEvent.OutputTuple,
    OracleDeployedEvent.OutputObject
  >;

  filters: {
    "OracleDeployed(address,address,string,string)": TypedContractEvent<
      OracleDeployedEvent.InputTuple,
      OracleDeployedEvent.OutputTuple,
      OracleDeployedEvent.OutputObject
    >;
    OracleDeployed: TypedContractEvent<
      OracleDeployedEvent.InputTuple,
      OracleDeployedEvent.OutputTuple,
      OracleDeployedEvent.OutputObject
    >;
  };
}
