/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace OracleRegistry {
  export type ValidatorStruct = {
    validatorAddress: AddressLike;
    endpoint: string;
    isActive: boolean;
    validationCount: BigNumberish;
    lastValidation: BigNumberish;
  };

  export type ValidatorStructOutput = [
    validatorAddress: string,
    endpoint: string,
    isActive: boolean,
    validationCount: bigint,
    lastValidation: bigint
  ] & {
    validatorAddress: string;
    endpoint: string;
    isActive: boolean;
    validationCount: bigint;
    lastValidation: bigint;
  };

  export type OracleStruct = {
    oracleAddress: AddressLike;
    creator: AddressLike;
    name: string;
    oracleType: string;
    updateFrequency: BigNumberish;
    consensusThreshold: BigNumberish;
    isActive: boolean;
    createdAt: BigNumberish;
    lastUpdate: BigNumberish;
  };

  export type OracleStructOutput = [
    oracleAddress: string,
    creator: string,
    name: string,
    oracleType: string,
    updateFrequency: bigint,
    consensusThreshold: bigint,
    isActive: boolean,
    createdAt: bigint,
    lastUpdate: bigint
  ] & {
    oracleAddress: string;
    creator: string;
    name: string;
    oracleType: string;
    updateFrequency: bigint;
    consensusThreshold: bigint;
    isActive: boolean;
    createdAt: bigint;
    lastUpdate: bigint;
  };
}

export interface OracleRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "activeValidatorCount"
      | "addValidator"
      | "allOracles"
      | "deactivateOracle"
      | "getActiveValidators"
      | "getAllOracles"
      | "getOracle"
      | "getOracleCount"
      | "getUserOracles"
      | "isRegisteredOracle"
      | "oracles"
      | "owner"
      | "recordUpdate"
      | "registerOracle"
      | "removeValidator"
      | "renounceOwnership"
      | "transferOwnership"
      | "userOracles"
      | "validatorIndex"
      | "validators"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DataUpdated"
      | "OracleDeactivated"
      | "OracleRegistered"
      | "OwnershipTransferred"
      | "ValidatorAdded"
      | "ValidatorRemoved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "activeValidatorCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addValidator",
    values: [BigNumberish, AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "allOracles",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveValidators",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllOracles",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getOracleCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserOracles",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRegisteredOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "oracles",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordUpdate",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerOracle",
    values: [AddressLike, string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeValidator",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userOracles",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "validatorIndex",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "validators",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "activeValidatorCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allOracles", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deactivateOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveValidators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllOracles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getOracle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getOracleCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserOracles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRegisteredOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "oracles", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userOracles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validatorIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "validators", data: BytesLike): Result;
}

export namespace DataUpdatedEvent {
  export type InputTuple = [oracle: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [oracle: string, timestamp: bigint];
  export interface OutputObject {
    oracle: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OracleDeactivatedEvent {
  export type InputTuple = [oracleAddress: AddressLike];
  export type OutputTuple = [oracleAddress: string];
  export interface OutputObject {
    oracleAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OracleRegisteredEvent {
  export type InputTuple = [
    oracleAddress: AddressLike,
    creator: AddressLike,
    name: string,
    oracleType: string
  ];
  export type OutputTuple = [
    oracleAddress: string,
    creator: string,
    name: string,
    oracleType: string
  ];
  export interface OutputObject {
    oracleAddress: string;
    creator: string;
    name: string;
    oracleType: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidatorAddedEvent {
  export type InputTuple = [
    validator: AddressLike,
    endpoint: string,
    index: BigNumberish
  ];
  export type OutputTuple = [
    validator: string,
    endpoint: string,
    index: bigint
  ];
  export interface OutputObject {
    validator: string;
    endpoint: string;
    index: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidatorRemovedEvent {
  export type InputTuple = [validator: AddressLike, index: BigNumberish];
  export type OutputTuple = [validator: string, index: bigint];
  export interface OutputObject {
    validator: string;
    index: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface OracleRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): OracleRegistry;
  waitForDeployment(): Promise<this>;

  interface: OracleRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  activeValidatorCount: TypedContractMethod<[], [bigint], "view">;

  addValidator: TypedContractMethod<
    [_index: BigNumberish, _validatorAddress: AddressLike, _endpoint: string],
    [void],
    "nonpayable"
  >;

  allOracles: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  deactivateOracle: TypedContractMethod<
    [_oracleAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  getActiveValidators: TypedContractMethod<
    [],
    [
      [
        OracleRegistry.ValidatorStructOutput,
        OracleRegistry.ValidatorStructOutput,
        OracleRegistry.ValidatorStructOutput,
        OracleRegistry.ValidatorStructOutput,
        OracleRegistry.ValidatorStructOutput
      ]
    ],
    "view"
  >;

  getAllOracles: TypedContractMethod<[], [string[]], "view">;

  getOracle: TypedContractMethod<
    [_oracleAddress: AddressLike],
    [OracleRegistry.OracleStructOutput],
    "view"
  >;

  getOracleCount: TypedContractMethod<[], [bigint], "view">;

  getUserOracles: TypedContractMethod<[_user: AddressLike], [string[]], "view">;

  isRegisteredOracle: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  oracles: TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint
      ] & {
        oracleAddress: string;
        creator: string;
        name: string;
        oracleType: string;
        updateFrequency: bigint;
        consensusThreshold: bigint;
        isActive: boolean;
        createdAt: bigint;
        lastUpdate: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  recordUpdate: TypedContractMethod<
    [_oracleAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  registerOracle: TypedContractMethod<
    [
      _oracleAddress: AddressLike,
      _name: string,
      _oracleType: string,
      _updateFrequency: BigNumberish,
      _consensusThreshold: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  removeValidator: TypedContractMethod<
    [_index: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  userOracles: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  validatorIndex: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  validators: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, boolean, bigint, bigint] & {
        validatorAddress: string;
        endpoint: string;
        isActive: boolean;
        validationCount: bigint;
        lastValidation: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "activeValidatorCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addValidator"
  ): TypedContractMethod<
    [_index: BigNumberish, _validatorAddress: AddressLike, _endpoint: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "allOracles"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "deactivateOracle"
  ): TypedContractMethod<[_oracleAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getActiveValidators"
  ): TypedContractMethod<
    [],
    [
      [
        OracleRegistry.ValidatorStructOutput,
        OracleRegistry.ValidatorStructOutput,
        OracleRegistry.ValidatorStructOutput,
        OracleRegistry.ValidatorStructOutput,
        OracleRegistry.ValidatorStructOutput
      ]
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAllOracles"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getOracle"
  ): TypedContractMethod<
    [_oracleAddress: AddressLike],
    [OracleRegistry.OracleStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOracleCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserOracles"
  ): TypedContractMethod<[_user: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "isRegisteredOracle"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "oracles"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint
      ] & {
        oracleAddress: string;
        creator: string;
        name: string;
        oracleType: string;
        updateFrequency: bigint;
        consensusThreshold: bigint;
        isActive: boolean;
        createdAt: bigint;
        lastUpdate: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordUpdate"
  ): TypedContractMethod<[_oracleAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerOracle"
  ): TypedContractMethod<
    [
      _oracleAddress: AddressLike,
      _name: string,
      _oracleType: string,
      _updateFrequency: BigNumberish,
      _consensusThreshold: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeValidator"
  ): TypedContractMethod<[_index: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userOracles"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "validatorIndex"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "validators"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, boolean, bigint, bigint] & {
        validatorAddress: string;
        endpoint: string;
        isActive: boolean;
        validationCount: bigint;
        lastValidation: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "DataUpdated"
  ): TypedContractEvent<
    DataUpdatedEvent.InputTuple,
    DataUpdatedEvent.OutputTuple,
    DataUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OracleDeactivated"
  ): TypedContractEvent<
    OracleDeactivatedEvent.InputTuple,
    OracleDeactivatedEvent.OutputTuple,
    OracleDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "OracleRegistered"
  ): TypedContractEvent<
    OracleRegisteredEvent.InputTuple,
    OracleRegisteredEvent.OutputTuple,
    OracleRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ValidatorAdded"
  ): TypedContractEvent<
    ValidatorAddedEvent.InputTuple,
    ValidatorAddedEvent.OutputTuple,
    ValidatorAddedEvent.OutputObject
  >;
  getEvent(
    key: "ValidatorRemoved"
  ): TypedContractEvent<
    ValidatorRemovedEvent.InputTuple,
    ValidatorRemovedEvent.OutputTuple,
    ValidatorRemovedEvent.OutputObject
  >;

  filters: {
    "DataUpdated(address,uint256)": TypedContractEvent<
      DataUpdatedEvent.InputTuple,
      DataUpdatedEvent.OutputTuple,
      DataUpdatedEvent.OutputObject
    >;
    DataUpdated: TypedContractEvent<
      DataUpdatedEvent.InputTuple,
      DataUpdatedEvent.OutputTuple,
      DataUpdatedEvent.OutputObject
    >;

    "OracleDeactivated(address)": TypedContractEvent<
      OracleDeactivatedEvent.InputTuple,
      OracleDeactivatedEvent.OutputTuple,
      OracleDeactivatedEvent.OutputObject
    >;
    OracleDeactivated: TypedContractEvent<
      OracleDeactivatedEvent.InputTuple,
      OracleDeactivatedEvent.OutputTuple,
      OracleDeactivatedEvent.OutputObject
    >;

    "OracleRegistered(address,address,string,string)": TypedContractEvent<
      OracleRegisteredEvent.InputTuple,
      OracleRegisteredEvent.OutputTuple,
      OracleRegisteredEvent.OutputObject
    >;
    OracleRegistered: TypedContractEvent<
      OracleRegisteredEvent.InputTuple,
      OracleRegisteredEvent.OutputTuple,
      OracleRegisteredEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ValidatorAdded(address,string,uint256)": TypedContractEvent<
      ValidatorAddedEvent.InputTuple,
      ValidatorAddedEvent.OutputTuple,
      ValidatorAddedEvent.OutputObject
    >;
    ValidatorAdded: TypedContractEvent<
      ValidatorAddedEvent.InputTuple,
      ValidatorAddedEvent.OutputTuple,
      ValidatorAddedEvent.OutputObject
    >;

    "ValidatorRemoved(address,uint256)": TypedContractEvent<
      ValidatorRemovedEvent.InputTuple,
      ValidatorRemovedEvent.OutputTuple,
      ValidatorRemovedEvent.OutputObject
    >;
    ValidatorRemoved: TypedContractEvent<
      ValidatorRemovedEvent.InputTuple,
      ValidatorRemovedEvent.OutputTuple,
      ValidatorRemovedEvent.OutputObject
    >;
  };
}
