/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SubscriptionManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "COST_PER_CALL"
      | "FEEDS_DISCOUNT"
      | "USDC_DECIMALS"
      | "addCredits"
      | "canMakeCall"
      | "credits"
      | "feedsToken"
      | "getETHPrice"
      | "getFeedsPrice"
      | "getSubscription"
      | "grantEnterpriseSubscription"
      | "monthlyBills"
      | "owner"
      | "payBill"
      | "plans"
      | "priceOracle"
      | "recordAPICall"
      | "renounceOwnership"
      | "setFeedsToken"
      | "subscribeWithETH"
      | "subscribeWithFEEDS"
      | "subscribeWithUSDC"
      | "subscriptions"
      | "transferOwnership"
      | "treasury"
      | "updatePlan"
      | "updateTreasury"
      | "usdc"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "APICallRecorded"
      | "BillPaid"
      | "CreditsAdded"
      | "OwnershipTransferred"
      | "Subscribed"
      | "SubscriptionRenewed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "COST_PER_CALL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FEEDS_DISCOUNT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "USDC_DECIMALS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addCredits",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "canMakeCall",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "credits",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "feedsToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getETHPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFeedsPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSubscription",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantEnterpriseSubscription",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "monthlyBills",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "payBill", values?: undefined): string;
  encodeFunctionData(functionFragment: "plans", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "priceOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recordAPICall",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setFeedsToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "subscribeWithETH",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "subscribeWithFEEDS",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "subscribeWithUSDC",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "subscriptions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updatePlan",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "updateTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "COST_PER_CALL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FEEDS_DISCOUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "USDC_DECIMALS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addCredits", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "canMakeCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "credits", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "feedsToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getETHPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFeedsPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantEnterpriseSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "monthlyBills",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "payBill", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "plans", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "priceOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordAPICall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeedsToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "subscribeWithETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "subscribeWithFEEDS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "subscribeWithUSDC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "subscriptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "updatePlan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
}

export namespace APICallRecordedEvent {
  export type InputTuple = [
    user: AddressLike,
    oracle: AddressLike,
    cost: BigNumberish
  ];
  export type OutputTuple = [user: string, oracle: string, cost: bigint];
  export interface OutputObject {
    user: string;
    oracle: string;
    cost: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BillPaidEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CreditsAddedEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscribedEvent {
  export type InputTuple = [
    user: AddressLike,
    tier: BigNumberish,
    expiresAt: BigNumberish
  ];
  export type OutputTuple = [user: string, tier: bigint, expiresAt: bigint];
  export interface OutputObject {
    user: string;
    tier: bigint;
    expiresAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionRenewedEvent {
  export type InputTuple = [
    user: AddressLike,
    tier: BigNumberish,
    expiresAt: BigNumberish
  ];
  export type OutputTuple = [user: string, tier: bigint, expiresAt: bigint];
  export interface OutputObject {
    user: string;
    tier: bigint;
    expiresAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SubscriptionManager extends BaseContract {
  connect(runner?: ContractRunner | null): SubscriptionManager;
  waitForDeployment(): Promise<this>;

  interface: SubscriptionManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  COST_PER_CALL: TypedContractMethod<[], [bigint], "view">;

  FEEDS_DISCOUNT: TypedContractMethod<[], [bigint], "view">;

  USDC_DECIMALS: TypedContractMethod<[], [bigint], "view">;

  addCredits: TypedContractMethod<
    [amountUSDC: BigNumberish],
    [void],
    "nonpayable"
  >;

  canMakeCall: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  credits: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  feedsToken: TypedContractMethod<[], [string], "view">;

  getETHPrice: TypedContractMethod<
    [usdcAmount: BigNumberish],
    [bigint],
    "view"
  >;

  getFeedsPrice: TypedContractMethod<
    [usdcAmount: BigNumberish],
    [bigint],
    "view"
  >;

  getSubscription: TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        tier: bigint;
        expiresAt: bigint;
        monthlyLimit: bigint;
        usedThisMonth: bigint;
        remainingCalls: bigint;
        creditBalance: bigint;
        outstandingBill: bigint;
      }
    ],
    "view"
  >;

  grantEnterpriseSubscription: TypedContractMethod<
    [
      user: AddressLike,
      callLimit: BigNumberish,
      updateFrequency: BigNumberish,
      durationDays: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  monthlyBills: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  payBill: TypedContractMethod<[], [void], "nonpayable">;

  plans: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, boolean] & {
        priceUSDC: bigint;
        callLimit: bigint;
        updateFrequency: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  priceOracle: TypedContractMethod<[], [string], "view">;

  recordAPICall: TypedContractMethod<
    [user: AddressLike, oracle: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setFeedsToken: TypedContractMethod<
    [_feedsToken: AddressLike],
    [void],
    "nonpayable"
  >;

  subscribeWithETH: TypedContractMethod<
    [tier: BigNumberish],
    [void],
    "payable"
  >;

  subscribeWithFEEDS: TypedContractMethod<
    [tier: BigNumberish],
    [void],
    "nonpayable"
  >;

  subscribeWithUSDC: TypedContractMethod<
    [tier: BigNumberish],
    [void],
    "nonpayable"
  >;

  subscriptions: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        tier: bigint;
        expiresAt: bigint;
        monthlyLimit: bigint;
        usedThisMonth: bigint;
        periodStart: bigint;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  updatePlan: TypedContractMethod<
    [
      tier: BigNumberish,
      priceUSDC: BigNumberish,
      callLimit: BigNumberish,
      updateFrequency: BigNumberish,
      active: boolean
    ],
    [void],
    "nonpayable"
  >;

  updateTreasury: TypedContractMethod<
    [newTreasury: AddressLike],
    [void],
    "nonpayable"
  >;

  usdc: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "COST_PER_CALL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FEEDS_DISCOUNT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "USDC_DECIMALS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addCredits"
  ): TypedContractMethod<[amountUSDC: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "canMakeCall"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "credits"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "feedsToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getETHPrice"
  ): TypedContractMethod<[usdcAmount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getFeedsPrice"
  ): TypedContractMethod<[usdcAmount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSubscription"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        tier: bigint;
        expiresAt: bigint;
        monthlyLimit: bigint;
        usedThisMonth: bigint;
        remainingCalls: bigint;
        creditBalance: bigint;
        outstandingBill: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantEnterpriseSubscription"
  ): TypedContractMethod<
    [
      user: AddressLike,
      callLimit: BigNumberish,
      updateFrequency: BigNumberish,
      durationDays: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "monthlyBills"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "payBill"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "plans"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, boolean] & {
        priceUSDC: bigint;
        callLimit: bigint;
        updateFrequency: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "priceOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordAPICall"
  ): TypedContractMethod<
    [user: AddressLike, oracle: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFeedsToken"
  ): TypedContractMethod<[_feedsToken: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "subscribeWithETH"
  ): TypedContractMethod<[tier: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "subscribeWithFEEDS"
  ): TypedContractMethod<[tier: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "subscribeWithUSDC"
  ): TypedContractMethod<[tier: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "subscriptions"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        tier: bigint;
        expiresAt: bigint;
        monthlyLimit: bigint;
        usedThisMonth: bigint;
        periodStart: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "updatePlan"
  ): TypedContractMethod<
    [
      tier: BigNumberish,
      priceUSDC: BigNumberish,
      callLimit: BigNumberish,
      updateFrequency: BigNumberish,
      active: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateTreasury"
  ): TypedContractMethod<[newTreasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "APICallRecorded"
  ): TypedContractEvent<
    APICallRecordedEvent.InputTuple,
    APICallRecordedEvent.OutputTuple,
    APICallRecordedEvent.OutputObject
  >;
  getEvent(
    key: "BillPaid"
  ): TypedContractEvent<
    BillPaidEvent.InputTuple,
    BillPaidEvent.OutputTuple,
    BillPaidEvent.OutputObject
  >;
  getEvent(
    key: "CreditsAdded"
  ): TypedContractEvent<
    CreditsAddedEvent.InputTuple,
    CreditsAddedEvent.OutputTuple,
    CreditsAddedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Subscribed"
  ): TypedContractEvent<
    SubscribedEvent.InputTuple,
    SubscribedEvent.OutputTuple,
    SubscribedEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionRenewed"
  ): TypedContractEvent<
    SubscriptionRenewedEvent.InputTuple,
    SubscriptionRenewedEvent.OutputTuple,
    SubscriptionRenewedEvent.OutputObject
  >;

  filters: {
    "APICallRecorded(address,address,uint256)": TypedContractEvent<
      APICallRecordedEvent.InputTuple,
      APICallRecordedEvent.OutputTuple,
      APICallRecordedEvent.OutputObject
    >;
    APICallRecorded: TypedContractEvent<
      APICallRecordedEvent.InputTuple,
      APICallRecordedEvent.OutputTuple,
      APICallRecordedEvent.OutputObject
    >;

    "BillPaid(address,uint256)": TypedContractEvent<
      BillPaidEvent.InputTuple,
      BillPaidEvent.OutputTuple,
      BillPaidEvent.OutputObject
    >;
    BillPaid: TypedContractEvent<
      BillPaidEvent.InputTuple,
      BillPaidEvent.OutputTuple,
      BillPaidEvent.OutputObject
    >;

    "CreditsAdded(address,uint256)": TypedContractEvent<
      CreditsAddedEvent.InputTuple,
      CreditsAddedEvent.OutputTuple,
      CreditsAddedEvent.OutputObject
    >;
    CreditsAdded: TypedContractEvent<
      CreditsAddedEvent.InputTuple,
      CreditsAddedEvent.OutputTuple,
      CreditsAddedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Subscribed(address,uint8,uint256)": TypedContractEvent<
      SubscribedEvent.InputTuple,
      SubscribedEvent.OutputTuple,
      SubscribedEvent.OutputObject
    >;
    Subscribed: TypedContractEvent<
      SubscribedEvent.InputTuple,
      SubscribedEvent.OutputTuple,
      SubscribedEvent.OutputObject
    >;

    "SubscriptionRenewed(address,uint8,uint256)": TypedContractEvent<
      SubscriptionRenewedEvent.InputTuple,
      SubscriptionRenewedEvent.OutputTuple,
      SubscriptionRenewedEvent.OutputObject
    >;
    SubscriptionRenewed: TypedContractEvent<
      SubscriptionRenewedEvent.InputTuple,
      SubscriptionRenewedEvent.OutputTuple,
      SubscriptionRenewedEvent.OutputObject
    >;
  };
}
