/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IFixrFeeSplitter } from "./IFixrFeeSplitter";
export type { IFixrStaking } from "./IFixrStaking";
