/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IClawgFeeSplitter } from "./IClawgFeeSplitter";
export type { IClawgStaking } from "./IClawgStaking";
export type { IFixrFeeSplitter } from "./IFixrFeeSplitter";
export type { IFixrStaking } from "./IFixrStaking";
