-- Proposals table for Fixr's autonomous ideation system
-- These are project ideas generated by the agent itself, not user-requested tasks

CREATE TABLE IF NOT EXISTS proposals (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  rationale TEXT NOT NULL,
  chain TEXT, -- ethereum, base, monad, solana (optional)
  category TEXT NOT NULL DEFAULT 'experiment', -- defi, nft, social, infra, tooling, experiment
  confidence TEXT NOT NULL DEFAULT 'medium', -- high, medium, low
  estimated_impact TEXT,
  inspirations JSONB DEFAULT '[]'::jsonb, -- array of trend/builder inspirations
  status TEXT NOT NULL DEFAULT 'proposed', -- proposed, approved, rejected, converted
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  reviewed_at TIMESTAMP WITH TIME ZONE
);

-- Index for status queries
CREATE INDEX IF NOT EXISTS idx_proposals_status ON proposals(status);

-- Index for created_at for recent proposals
CREATE INDEX IF NOT EXISTS idx_proposals_created_at ON proposals(created_at DESC);

-- Index for category filtering
CREATE INDEX IF NOT EXISTS idx_proposals_category ON proposals(category);

-- RLS policies
ALTER TABLE proposals ENABLE ROW LEVEL SECURITY;

-- Allow service role full access
CREATE POLICY "Service role can manage proposals"
  ON proposals
  FOR ALL
  USING (true)
  WITH CHECK (true);

-- Comments for documentation
COMMENT ON TABLE proposals IS 'Agent-initiated project proposals from Fixr autonomous ideation system';
COMMENT ON COLUMN proposals.rationale IS 'Why this project is worth building - what trend or gap it addresses';
COMMENT ON COLUMN proposals.confidence IS 'How confident the agent is this would succeed';
COMMENT ON COLUMN proposals.inspirations IS 'Trends or builders that inspired this proposal';
COMMENT ON COLUMN proposals.status IS 'proposed -> approved/rejected, approved -> converted (to task)';
