import Link from 'next/link';

export default function DisclaimerPage() {
  return (
    <main className="min-h-screen bg-[#0a0a0a] text-white">
      <div className="max-w-4xl mx-auto px-6 py-16">
        <Link
          href="/"
          className="text-gray-400 hover:text-white transition-colors inline-block mb-8"
        >
          ← Back to home
        </Link>

        <h1 className="text-4xl font-bold mb-4">Disclaimer</h1>
        <p className="text-gray-500 mb-12">Effective Date: January 31, 2026</p>

        <div className="space-y-8 text-gray-400">
          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">No Warranty</h2>
            <p>
              Fixr is an experimental autonomous AI agent provided &quot;as is&quot; without warranty
              of any kind, either expressed or implied. We make no representations or warranties
              regarding the accuracy, reliability, functionality, or performance of the Service
              or any outputs it produces.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">AI-Generated Content</h2>
            <p className="mb-4">
              All content, code, and outputs generated by Fixr are produced by an autonomous AI
              system powered by Claude. While we strive for accuracy and quality:
            </p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>Generated content may contain errors, bugs, or security vulnerabilities</li>
              <li>Outputs should always be thoroughly reviewed and tested before use</li>
              <li>We cannot guarantee the suitability of any generated content for your specific needs</li>
              <li>AI-generated code may not follow best practices or your coding standards</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">Use at Your Own Risk</h2>
            <p className="mb-4">
              You acknowledge that using Fixr and implementing any of its outputs is entirely
              at your own risk. We strongly recommend:
            </p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>Thoroughly testing all generated code before deployment</li>
              <li>Maintaining backups of your projects before allowing modifications</li>
              <li>Reviewing all code changes in a staging environment first</li>
              <li>Never deploying AI-generated code directly to production without review</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">Not Financial or Legal Advice</h2>
            <p>
              Nothing provided by Fixr should be construed as financial, legal, tax, or
              professional advice of any kind. The Service is intended solely for software
              development assistance. For smart contract deployments, token-related activities,
              or any blockchain operations, always consult with qualified legal and financial
              professionals.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">External Links & Deployments</h2>
            <p>
              Fixr may generate links to external websites, deploy code to third-party services
              (GitHub, Vercel, etc.), or interact with blockchain networks. We have no control
              over these external services and are not responsible for their availability,
              security, or any consequences of deployments made through them.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">Experimental Nature</h2>
            <p>
              <span className="text-white font-semibold">Important:</span> Fixr is an experimental
              autonomous agent in active development. Features, capabilities, and behaviors may
              change without notice. The Service may experience downtime, errors, unexpected
              behaviors, or produce incorrect outputs as part of its experimental nature.
              Use accordingly and always maintain human oversight of all operations.
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
