import Link from 'next/link';

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-[#0a0a0a] text-white">
      <div className="max-w-4xl mx-auto px-6 py-16">
        <Link
          href="/"
          className="text-gray-400 hover:text-white transition-colors inline-block mb-8"
        >
          ← Back to home
        </Link>

        <h1 className="text-4xl font-bold mb-4">Terms of Service</h1>
        <p className="text-gray-500 mb-12">Effective Date: January 31, 2026</p>

        <div className="space-y-8 text-gray-400">
          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">1. Acceptance of Terms</h2>
            <p>
              By accessing or using Fixr (&quot;the Service&quot;), an autonomous AI agent powered by Claude,
              you agree to be bound by these Terms of Service. If you do not agree to these terms,
              please do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">2. Use of Service</h2>
            <p className="mb-4">
              Fixr is an experimental autonomous builder agent designed to assist with software
              development tasks. The Service is provided on an &quot;as-is&quot; basis. You acknowledge that:
            </p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>Fixr operates autonomously and may produce unpredictable results</li>
              <li>All outputs should be reviewed before implementation</li>
              <li>You are responsible for any use of the Service&apos;s outputs</li>
              <li>The Service may create, modify, or deploy code on your behalf</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">3. Intellectual Property</h2>
            <p>
              Code and content generated by Fixr may be used freely by you. However, the Service
              itself, including its underlying systems, branding, and infrastructure, remains the
              property of its creators. You may not attempt to reverse engineer, copy, or replicate
              the Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">4. Limitation of Liability</h2>
            <p>
              To the fullest extent permitted by law, Fixr and its creators shall not be liable
              for any indirect, incidental, special, consequential, or punitive damages, or any
              loss of profits or revenues, whether incurred directly or indirectly, or any loss
              of data, use, goodwill, or other intangible losses resulting from your use of the Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">5. Changes to Terms</h2>
            <p>
              We reserve the right to modify these Terms of Service at any time. We will notify
              users of any material changes by updating the effective date. Your continued use
              of the Service after such modifications constitutes acceptance of the updated terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">6. Contact</h2>
            <p>
              If you have any questions about these Terms of Service, please reach out via{' '}
              <a
                href="https://x.com/Fixr21718"
                target="_blank"
                rel="noopener noreferrer"
                className="text-white hover:text-gray-300 transition-colors underline"
              >
                X
              </a>{' '}
              or{' '}
              <a
                href="https://farcaster.xyz/fixr"
                target="_blank"
                rel="noopener noreferrer"
                className="text-white hover:text-gray-300 transition-colors underline"
              >
                Farcaster
              </a>
              .
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
